# Reload configuration easily
unbind r
bind r source-file ~/.tmux.conf

# Set leader to crtl+x
set -g prefix C-x

set -g mouse on

# Adding vim motions to pane swapping
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Status bar top
set-option -g status-position top

# split panes remap leader-x + shift _ or | (Be aware, -v and -h are causing comments to apper weird. This doesnt seem to change functionality though)
bind-key _ split-window -v
bind-key | split-window -h

# Change to use my default shell
set-option -g default-shell /bin/fish


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# Save sessions across reboots
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
# Allow copying to system clipboard
set -g @plugin 'tmux-plugins/tmux-yank'

# Powerline
set -g @plugin 'erikw/tmux-powerline'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Themes
#set -g @plugin 'egel/tmux-gruvbox'
#set -g @tmux-gruvbox 'dark' # or 'light', 'dark-transparent', 'light-transparent'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
