# You can put your preferred keybinds here
# https://wiki.hyprland.org/Configuring/Binds/

# Terminal
bind = $mainMod, return, exec, foot

# Layout Manager
bind = $mainMod SHIFT, L, exec, ~/.config/hypr/scripts/layout_manager_unified.py

# Window resizing
bind = $mainMod SHIFT, left, resizeactive, -40 0
bind = $mainMod SHIFT, right, resizeactive, 40 0
bind = $mainMod SHIFT, up, resizeactive, 0 -40
bind = $mainMod SHIFT, down, resizeactive, 0 40



