hl.bind("SUPER + Z", hl.dsp.cursor.move({ x = 100, y = 200 }))
hl.window_rule({ match = { title = "^lay - Window 1 - foot$" }, float = true, size = {800, 600}, move = {10, 20} })
hl.window_rule({ match = { class = "^firefox$", workspace = "3" }, float = true, size = {800, 600}, move = {10, 20} })
hl.window_rule({ match = { title = "^lay - Window 1 - foot$" }, workspace = "3" })
hl.bind("SUPER + X", hl.dsp.window.tag({ tag = "+lay_foo_ws_3_pos_0", window = "address:0x55d1c0ffee" }))
hl.bind("SUPER + C", hl.dsp.exec_cmd("firefox --new-window \"x y\"", { workspace = "3 silent", float = true, size = {800, 600}, move = {10, 20} }))
hl.bind("SUPER + V", hl.dsp.exec_cmd("zenity --info", { float = true }))
hl.bind("SUPER + B", hl.dsp.window.resize({ x = 800, y = 600, window = "address:0x55d1c0ffee" }))
hl.bind("SUPER + N", hl.dsp.window.move({ x = 10, y = 20, window = "address:0x55d1c0ffee" }))
hl.bind("SUPER + M", hl.dsp.window.float({ action = "toggle", window = "address:0x55d1c0ffee" }))
hl.bind("SUPER + A", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + S", hl.dsp.window.move({ workspace = 3, follow = false, window = "address:0x55d1c0ffee" }))
hl.bind("SUPER + D", hl.dsp.window.resize({ x = 800, y = 600, window = "address:0x55d1c0ffee" }))
hl.bind("SUPER + F", hl.dsp.window.move({ x = 10, y = 20, window = "address:0x55d1c0ffee" }))
hl.bind("SUPER + G", hl.dsp.focus({ window = "address:0x55d1c0ffee" }))
hl.bind("SUPER + H", hl.dsp.window.move({ workspace = "special:foo", follow = true, window = "address:0x55d1c0ffee" }))
