# Float all windows by default with consistent size
windowrule = float on, match:class (.*)
windowrule = size 75% 80%, match:class (.*)

# Foot terminal - semi-transparent
windowrule = opacity 0.92 0.88, match:class foot

# ╻ ╻┏━┓┏━┓╻┏ ┏━┓┏━┓┏━┓┏━╸┏━╸   ┏━┓╻ ╻╻  ┏━╸┏━┓
# ┃╻┃┃ ┃┣┳┛┣┻┓┗━┓┣━┛┣━┫┃  ┣╸    ┣┳┛┃ ┃┃  ┣╸ ┗━┓
# ┗┻┛┗━┛╹┗╸╹ ╹┗━┛╹  ╹ ╹┗━╸┗━╸   ╹┗╸┗━┛┗━╸┗━╸┗━┛

workspace=special,gapsin:24,gapsout:64
workspace=special:browser,gapsin:24,gapsout:64
workspace=special:document,gapsin:24,gapsout:64
workspace=special:media,gapsin:24,gapsout:64

# Route apps to special workspaces
windowrule = workspace special:browser silent, match:class firefox
windowrule = workspace special:document silent, match:class org.pwmt.zathura
windowrule = workspace special:media silent, match:class mpv

# ╻  ┏━┓╻ ╻┏━╸┏━┓   ┏━┓╻ ╻╻  ┏━╸┏━┓
# ┃  ┣━┫┗┳┛┣╸ ┣┳┛   ┣┳┛┃ ┃┃  ┣╸ ┗━┓
# ┗━╸╹ ╹ ╹ ┗━╸╹┗╸   ╹┗╸┗━┛┗━╸┗━╸┗━┛

layerrule = blur on, match:namespace logout
layerrule = no_anim on, match:namespace bar
layerrule = no_anim on, match:namespace notifications
layerrule = no_anim on, match:namespace audio_controls
layerrule = no_anim on, match:namespace system_controls
layerrule = no_anim on, match:namespace calendar
