# ╻ ╻╻┏┓╻╺┳┓┏━┓╻ ╻   ┏━┓╻ ╻╻  ┏━╸┏━┓
# ┃╻┃┃┃┗┫ ┃┃┃ ┃┃╻┃   ┣┳┛┃ ┃┃  ┣╸ ┗━┓
# ┗┻┛╹╹ ╹╺┻┛┗━┛┗┻┛   ╹┗╸┗━┛┗━╸┗━╸┗━┛

windowrulev2 = float,class:^(net.davidotek.pupgui2)$ #ProtonUp-Qt
windowrulev2 = float,class:^(yad)$ #Protontricks-Gtk
windowrulev2 = float,class:^(qt5ct)$
windowrulev2 = float,class:^(nwg-look)$
windowrulev2 = float,class:^(org.kde.ark)$
windowrulev2 = float,class:^(pavucontrol)$
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,class:^(nm-applet)$
windowrulev2 = float,class:^(nm-connection-editor)$
windowrulev2 = float,class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrulev2 = float,class:^(com.obsproject.Studio)$,title:^(Controls)$
windowrulev2 = float,class:^(com.hyprland.layoutmanager)$
windowrulev2 = noborder,class:^(com.hyprland.layoutmanager)$
windowrulev2 = noshadow,class:^(com.hyprland.layoutmanager)$
windowrulev2 = float,class:^(org.pwmt.zathura)$
windowrulev2 = float,class:^(mpv)$

# Pin MPV and Zathura opened from Neovim (keeps them on top of other windows)
windowrulev2 = pin,title:^(nvim-mpv)$
windowrulev2 = pin,class:^(org.pwmt.zathura)$

# ╻ ╻┏━┓┏━┓╻┏ ┏━┓┏━┓┏━┓┏━╸┏━╸   ┏━┓╻ ╻╻  ┏━╸┏━┓
# ┃╻┃┃ ┃┣┳┛┣┻┓┗━┓┣━┛┣━┫┃  ┣╸    ┣┳┛┃ ┃┃  ┣╸ ┗━┓
# ┗┻┛┗━┛╹┗╸╹ ╹┗━┛╹  ╹ ╹┗━╸┗━╸   ╹┗╸┗━┛┗━╸┗━╸┗━┛

workspace=special,gapsin:24,gapsout:64

# ╻  ┏━┓╻ ╻┏━╸┏━┓   ┏━┓╻ ╻╻  ┏━╸┏━┓
# ┃  ┣━┫┗┳┛┣╸ ┣┳┛   ┣┳┛┃ ┃┃  ┣╸ ┗━┓
# ┗━╸╹ ╹ ╹ ┗━╸╹┗╸   ╹┗╸┗━┛┗━╸┗━╸┗━┛

layerrule = blur,logout
layerrule = noanim,bar
layerrule = noanim,notifications
layerrule = noanim,audio_controls
layerrule = noanim,system_controls
layerrule = noanim,calendar
